export const FETCHING_DATA = "FETCHING_DATA"
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS"
export const FETCHING_DATA_FAIL = "FETCHING_DATA_FAIL"

export const SWITCH_SWAPI_TYPE = "SWITCH_SWAPI_TYPE"